apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cryptopedia-web
  namespace: web
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: cryptopedia.kr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cryptopedia-web
                port:
                  number: 80
