apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cryptopedia-api.yaml
  - cryptopedia-web.yaml
  - cryptopedia-web-ingress.yaml

patchesStrategicMerge:
  - cryptopedia-api-image-patch.yaml
  - cryptopedia-web-image-patch.yaml
